package model

class EnStrings : Strings {
    override val appTitle = "ADB File Manager"
    override fun appVersion(version: String) = "Version $version"
    override val appDescription = "A simple and easy-to-use ADB file management tool supporting file transfer, editing and management."
    override val appChecking = "Checking..."
    override val appCheckUpdate = "Check for Updates"
    override val appViewOnGithub = "View on GitHub"
    override val appClose = "Close"
    override val appLater = "Later"
    override val appUpdateNow = "Update Now"
    override val appNewVersion = "New Version Available"
    override fun appNewVersionDetail(version: String) = "Version $version has been released"
    override val appUpdateContent = "Update Content:"
    override val appDontPromptAgain = "Don't prompt again"

    override val navRoot = "Root"
    override val navBack = "Back"
    override val navGoBack = "Go Back"

    override val fileDeleteConfirm = "Confirm Delete"
    override fun fileDeleteMessage(fileName: String) = "Are you sure you want to delete \"$fileName\"? This action cannot be undone."
    override val fileDelete = "Delete"
    override val fileCancel = "Cancel"
    override val fileSave = "Save"
    override val fileRename = "Rename"
    override val fileImportSuccess = "Files imported successfully"
    override fun fileImportFailed(error: String) = "Failed to import files: $error"
    override fun fileExportFailed(error: String) = "Failed to export file: $error"
    override val fileDeleteSuccess = "File deleted successfully"
    override fun fileDeleteFailed(error: String) = "Failed to delete file: $error"
    override val fileSaveSuccess = "File saved successfully"
    override fun fileSaveFailed(error: String) = "Failed to save file: $error"
    override val fileDownload = "Download"
    override val fileEdit = "Edit"
    override val fileNewFolder = "Create New Folder"
    override val fileNewFile = "Create New File"
    override val fileFolderName = "Folder Name"
    override val fileFolderNameInput = "Enter new folder name"
    override val fileFolderNameErrorInvalid = "Folder name cannot contain special characters like: / or \\"
    override val fileName = "File Name"
    override val fileNameInput = "Enter file name (e.g., note.txt)"
    override val fileContent = "File Content"
    override val fileContentInput = "Enter file content (optional)"
    override val fileCreate = "Create"
    override val fileNameEmptyError = "File name cannot be empty"
    override val fileNameInvalidError = "File name cannot contain special characters"
    override val fileLink = "Link"
    override val fileLinkDirectory = "Link Directory"
    override val fileDirectory = "Directory"
    override val fileModified = "Modified"
    override fun fileCharactersLines(chars: Int, lines: Int) = "$chars characters, $lines lines"

    override val editorTitle = "Edit"
    override fun editorTitleWithName(name: String) = "Edit - $name"
    override val editorFileEditor = "File Editor"
    override fun editorEncoding(encoding: String) = "Encoding: $encoding"
    override val editorEncodingLabel = "Encoding: "
    override val editorClose = "Close"
    override val editorFileContent = "Edit file content"
    override val editorModified = "Modified"
    override val editorCharactersLines = ""

    override val sortTitle = "Sort"
    override val sortTypeFolderFirst = "Type (Folders First)"
    override val sortTypeFileFirst = "Type (Files First)"
    override val sortNameAZ = "Name (A-Z)"
    override val sortDateOldest = "Date (Oldest)"
    override val sortDateNewest = "Date (Newest)"
    override val sortSizeSmallest = "Size (Smallest)"
    override val sortSizeLargest = "Size (Largest)"

    override val pathEdit = "Edit Path"
    override val pathInput = "Input Path"
    override val pathInputPlaceholder = "Enter target path"
    override fun pathInvalid(path: String) = "Invalid path: $path"
    override val pathAlreadyRoot = "Already at root directory"
    override val pathInvalidIndex = "Invalid index"
    override val pathCollapse = "Collapse"

    override val searchTitle = "Search Files"
    override val searchPlaceholder = "Search..."

    override val errorTitle = "Error"
    override val errorEmptyDirectory = "Current directory is empty"
    override val errorNoFiles = "No files or folders found"
    override val errorLoading = "Loading..."

    override val permissionDenied = "Permission denied"
    override val permissionInvalid = "Invalid path"

    override fun terminalCommandFailed(exitCode: Int, msg: String) = "Command failed (exitCode=$exitCode): $msg"

    override fun adbPermissionSet(path: String) = "ADB executable permission set: $path"
    override fun adbPermissionError(msg: String) = "Error setting ADB executable permission: $msg"

    // About dialog strings
    override val aboutTitle = "About"
    override val aboutDescription = "A simple and easy-to-use ADB file management tool supporting file transfer, editing and management."
    override val aboutViewOnGithub = "View on GitHub"
    override val aboutCheckUpdate = "Check for Updates"
    override val aboutChecking = "Checking..."
    override val aboutClose = "Close"

    // Theme strings
    override val themeFollowSystem = "Follow System"
    override val themeLight = "Light Mode"
    override val themeDark = "Dark Mode"
    override val themeToggle = "Toggle theme"
    override val languageToggle = "Toggle language"
    override val deviceToggle = "Switch device"

    // Language strings
    override val languageChinese = "中文"
    override val languageEnglish = "English"

    // Device strings
    override val deviceNotConnected = "Not Connected"
    override val deviceSelectMethod = "Please select connection method"

    // Window strings
    override val windowMinimize = "Minimize"
    override val windowClose = "Close"

    // Device connection strings
    override val deviceConnectUSB = "USB Connection"
    override val deviceConnectWireless = "Wireless Connection"
    override val deviceUSBGuide = "USB Connection Guide"
    override val deviceWirelessGuide = "Wireless Connection"
    override val deviceRefresh = "Refresh"
    override val deviceConnect = "Connect"
    override fun deviceUSBGuideStep1() = "Enable Developer Options on Android device:"
    override fun deviceUSBGuideStep2() = "Enable USB debugging:"
    override fun deviceUSBGuideStep3() = "Connect device:"
    override fun deviceUSBGuideStep4() = "Click refresh to check connection"
    override fun deviceWirelessGuideStep1() = "Ensure device and computer are on the same network"
    override fun deviceWirelessGuideStep2() = "Enable Wireless Debugging on device:"
    override fun deviceWirelessGuideStep3() = "Connection method:"
    override fun deviceWirelessGuideStep4() = "Method: Manually enter pairing info (paired devices may skip port and code)"
    override val deviceWirelessGuideIP = "IP Address"
    override val deviceWirelessGuidePort = "Port (default: 5555 if empty)"
    override val deviceWirelessGuidePairPort = "Pairing Port (optional)"
    override val deviceWirelessGuidePairCode = "Pairing Code (optional)"
    
    // Permission strings
    override val changePermissions = "Change Permissions"
    override val permissionChangeSuccess = "Permissions changed successfully"
    override fun permissionChangeFailed(error: String) = "Failed to change permissions: $error"
    override fun permissionCurrent(permissions: String) = "Current permissions: $permissions"
    override val permissionUseOctal = "Use octal"
    override val permissionOctalLabel = "Octal permissions (e.g., 755)"
    override val permissionOwner = "Owner (User)"
    override val permissionGroup = "Group"
    override val permissionOther = "Other"
    override val permissionRead = "Read"
    override val permissionWrite = "Write"
    override val permissionExecute = "Execute"
    
    // Bookmark strings
    override val addBookmark = "Add Bookmark"
    override val removeBookmark = "Remove Bookmark"
    override val bookmark = "Bookmark"
    override fun bookmarkPath(currentPath: String): String {
        return "Path: $currentPath"
    }
    override val bookmarkNameLabel = "Bookmark Name"
    override val bookmarkConfirm = "Add"
    override val bookmarkCancel = "Cancel"
    override val bookmarkEmpty = "No bookmarks yet"
    override val bookmarkAddCurrentPath = "Add current path"
    override val bookmarkAddedSuccess = "Bookmark added successfully"
    override fun bookmarkAddedFailed(error: String) = "Failed to add bookmark: $error"
    override val bookmarkRemovedSuccess = "Bookmark removed successfully"
    override fun bookmarkRemovedFailed(error: String) = "Failed to remove bookmark: $error"
    override val folderCreatedSuccess = "Folder created successfully"
    override fun folderCreatedFailed(error: String) = "Failed to create folder: $error"
    override val fileCreatedSuccess = "File created successfully"
    override fun fileCreatedFailed(error: String) = "Failed to create file: $error"
    override val renameSuccess = "Renamed successfully"
    override fun renameFailed(error: String) = error
    
    // Transfer strings
    override val transferFile = "Transfer File"
    override val transferPreparing = "Preparing..."
    override fun transferInProgress(percent: Int) = "Transferring... (~${percent}%)"
}
